# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/

singleuser:
  allowPrivilegeEscalation: yes
  cmd: null # Don't override the Dockerfile's cmd
  image:
    name: ghcr.io/chameleoncloud/jupyterlab-chameleon
  defaultUrl: "/lab"
  extraEnv:
    GRANT_SUDO: "yes"
    OS_KEYPAIR_PRIVATE_KEY: "/work/.ssh/id_rsa"
    OS_KEYPAIR_PUBLIC_KEY: "/work/.ssh/id_rsa.pub"
    CHOWN_EXTRA: "/work"
    CHOWN_EXTRA_OPTS: "-R"
    ARTIFACT_SHARING_OS_AUTH_TYPE: "v3password"
    ARTIFACT_SHARING_OS_USERNAME: "trovi"
    ARTIFACT_SHARING_OS_USER_DOMAIN_NAME: "default"
    ARTIFACT_SHARING_OS_PROJECT_NAME: "service"
    ARTIFACT_SHARING_OS_PROJECT_DOMAIN_NAME: "default"
  uid: 0
  memory:
    limit: 1G
    guarantee: 1G
  cpu:
    limit: .49
    guarantee: .49
  fsGid: 100
  storage:
    capacity: 512M
    homeMountPath: /work
    dynamic:
      storageClass: "cinder-csi"
  extraFiles:
    jupyter_notebook_config.json:
      mountPath: /etc/jupyter/jupyter_notebook_config.json
      data:
        MappingKernelManager:
          cull_idle_timeout: 3600
          cull_interval: 300
          cull_connected: false
  networkPolicy:
    enabled: false
  startTimeout: 300

hub:
  image:
    name: ghcr.io/chameleoncloud/jupyterhub-chameleon
  extraEnv:
    # If a user is in this project, they are admin
    OAUTH_ADMIN_PROJECT: "Chameleon"
    JUPYTERHUB_ALLOW_TOKEN_IN_URL: "true"
  networkPolicy:
    enabled: false
  config:
    JupyterHub:
      allow_named_servers: yes
      authenticator_class: "chameleon"
      spawner_class: "chameleon"
      cleanup_servers: no
      cleanup_proxy: no
      cookie_max_age_days: 30
    ChameleonSpawner:
      env_keep:
        - JUPYTERHUB_PUBLIC_URL
        - ARTIFACT_SHARING_OS_AUTH_TYPE
        - ARTIFACT_SHARING_OS_USERNAME
        - ARTIFACT_SHARING_OS_USER_DOMAIN_NAME
        - ARTIFACT_SHARING_OS_PROJECT_NAME
        - ARTIFACT_SHARING_OS_PROJECT_DOMAIN_NAME
        - TROVI_URL
      working_dir: "/work"
      notebook_dir: "/work"
      http_timeout: 1200
      start_timeout: 1200
    ChameleonKeycloakAuthenticator:
      login_service: "Chameleon"
    GenericOAuthenticator:
      login_service: "Chameleon"
      username_key: "preferred_username"
  loadRoles: # Custom roles so user can get their own token
    user:
      scopes: ["self", "admin:auth_state!user"]
    server:
      scopes: ["access:servers!user", "read:users:activity!user", "users:activity!user", "admin:auth_state!user"]
  extraConfig:
    chameleonConfig.py: |
      import os

      from jupyterhub_chameleon.handler import UserRedirectExperimentHandler
      from jupyterhub_chameleon.handler import TroviMetricHandler

      c.JupyterHub.extra_handlers = [
        (r"/import", UserRedirectExperimentHandler),
        (r"/api/trovi_metrics", TroviMetricHandler),
      ]

      import importlib.resources
      import jupyterhub_chameleon
      c.JupyterHub.template_paths = [
          "/usr/local/share/jupyterhub_chameleon/templates",
      ]
  pdb:
    enabled: false
  slug_scheme: "escape

cull:
  enabled: true

scheduling:
  userScheduler:
    enabled: false
    pdb:
      enabled: false
  podPriority:
    enabled: false
  userPlaceholder:
    enabled: false

prePuller:
  hook:
    enabled: false
  continuous:
    enabled: false

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
  - jupyter.dev.chameleon.savanna.tacc.cloud
  tls:
    - hosts:
      - jupyter.dev.chameleon.savanna.tacc.cloud
      secretName: certmanager-tls-chameleon-jupyterhub-prod-2
        #- hosts:
        #- jupyter.chameleon.savanna.tacc.cloud
        #secretName: certmanager-tls-chameleon-jupyterhub-tacc
  annotations:
      cert-manager.io/issuer: "letsencrypt"
      kubernetes.io/ingress.class: "nginx"


proxy:
  chp:
    networkPolicy:
      enabled: false
    pdb:
      enabled: false
  traefik:
    networkPolicy:
      enabled: false
  service:
    type: ClusterIP
  https:
    enabled: false
  traefik:
    extraInitContainers:
      # This startup delay can help the k8s container network interface setup
      # network routing of traffic to the pod, which is essential for the ACME
      # challenge submitted by Traefik on startup to acquire a TLS certificate.
      #
      # Sleeping for 7 seconds has been consistently sufficient to avoid issues
      # in GKE when this workaround was explored initially for GKE.
      #
      - name: startup-delay
        image: busybox:stable
        command: ["sh", "-c", "sleep 30"]
