# Things that shouldn't be in git
hub:
  config:
    GenericOAuthenticator:
      client_secret: ""
  extraEnv:
    OAUTH_CLIENT_SECRET: ""

imagePullSecret:
  create: yes
  registry: docker.chameleoncloud.org
  username: kolla
  password: 

# Uncomment this section and fill in the path to mount jupyterlab-chameleon
# into spawned containers for local dev.
#singleuser:
#  storage:
#    extraVolumes:
#    - name: jupyterlab-chameleon
#      hostPath:
#        path: # Path to local jupyterlab-chameleon repo
#    extraVolumeMounts:
#    - name: jupyterlab-chameleon
#      mountPath: /jupyterlab_chameleon
