singleuser:
  image:
    tag: "sha-403ed29"
    pullPolicy: "Always"
    pullSecrets:
      - name: image-pull-secret
  cloudMetadata:
    blockWithIptables: false
  extraEnv:
    JUPYTERHUB_PUBLIC_URL: https://dev.jupyter.chameleoncloud.org

hub:
  image:
    tag: "sha-b9b1bad"
    pullPolicy: "Always"
    pullSecrets:
      - name: image-pull-secret
  config:
    ChameleonKeycloakAuthenticator:
      keystone_auth_url: "https://dev.uc.chameleoncloud.org:5000/v3"
      keystone_default_region_name: "CHI@UC"
    GenericOAuthenticator:
      oauth_callback_url: "https://dev.jupyter.chameleoncloud.org/hub/oauth_callback"
      client_id: "jupyterhub-dev"
      authorize_url: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/auth"
      token_url: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/token"
      userdata_url: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/userinfo"
  extraEnv:
    TROVI_URL: "https://trovi-dev.chameleoncloud.org"
    KEYCLOAK_CLIENT_ID: "jupyterhub-dev"
    KEYCLOAK_TOKEN_URL: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/token"
    OAUTH_CLIENT_ID: "jupyterhub-dev"
debug:
  enabled: true
proxy:
  https:
    enabled: true
    hosts:
      - dev.jupyter.chameleoncloud.org
    letsencrypt:
      contactEmail: contact@chameleoncloud.org
  service:
    loadBalancerIP: 34.132.247.78
  traefik:
    extraInitContainers:
      # This startup delay can help the k8s container network interface setup
      # network routing of traffic to the pod, which is essential for the ACME
      # challenge submitted by Traefik on startup to acquire a TLS certificate.
      #
      # Sleeping for 7 seconds has been consistently sufficient to avoid issues
      # in GKE when this workaround was explored initially for GKE.
      # https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2601#issuecomment-1127600794
      #
      - name: startup-delay
        image: busybox:stable
        command: ["sh", "-c", "sleep 20"]
scheduling:
  podPriority:
    enabled: true
  userPlaceholder:
    replicas: 0
