# things that shouldn't be in git
hub:
  config:
    GenericOAuthenticator:
      client_secret: ""

imagePullSecret:
  create: yes
  registry: docker.chameleoncloud.org
  username: kolla
  password: 
