# Values unique to testing on local dev
singleuser:
  image:
    tag: dev
    pullPolicy: "Never" # Uses docker image from local machine
  extraEnv:
    JUPYTERHUB_PUBLIC_URL: http://127.0.0.1:8080

hub:
  db:
    type: sqlite-memory
  image:
    tag: "dev"
    pullPolicy: "Never" # Uses docker image from local machine
  config:
    JupyterHub:
      log_level: debug
    Application:
      log_level: debug
    ChameleonKeycloakAuthenticator:
      keystone_auth_url: "https://dev.uc.chameleoncloud.org:5000/v3"
      keystone_default_region_name: "CHI_DEV_UC"
    GenericOAuthenticator:
      oauth_callback_url: "http://127.0.0.1:8080/hub/oauth_callback"
      client_id: "jupyterhub-local-dev"
      authorize_url: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/auth"
      token_url: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/token"
      userdata_url: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/userinfo"
  extraEnv:
    TROVI_URL: "https://trovi-dev.chameleoncloud.org"
    DEBUG: "true"
debug:
  enabled: true
