singleuser:
  image:
    tag: "sha-7e9e231"
    pullPolicy: "Always"
  cloudMetadata:
    blockWithIptables: false
  extraEnv:
    JUPYTERHUB_PUBLIC_URL: https://jupyter.dev.chameleon.savanna.tacc.cloud

hub:
  image:
    tag: "sha-994ad0d"
    pullPolicy: "Always"
  config:
    ChameleonKeycloakAuthenticator:
      keystone_auth_url: "https://dev.uc.chameleoncloud.org:5000/v3"
      keystone_default_region_name: "CHI@UC"
    GenericOAuthenticator:
      oauth_callback_url: "https://jupyter.dev.chameleon.savanna.tacc.cloud/hub/oauth_callback"
      client_id: "jupyterhub-dev"
      authorize_url: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/auth"
      token_url: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/token"
      userdata_url: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/userinfo"
  extraEnv:
    TROVI_URL: "https://trovi-dev.chameleoncloud.org"
    KEYCLOAK_CLIENT_ID: "jupyterhub-dev"
    KEYCLOAK_TOKEN_URL: "https://auth.dev.chameleoncloud.org/auth/realms/chameleon/protocol/openid-connect/token"
    OAUTH_CLIENT_ID: "jupyterhub-dev"
  db:
    pvc:
      storageClassName: "cinder-csi"
debug:
  enabled: true
  #https:
    #enabled: true
      #hosts:
      #- jupyter.chameleon.savanna.tacc.cloud
        #letsencrypt:
      #contactEmail: contact@chameleoncloud.org
        #service:
    #loadBalancerIP: 34.132.247.78
